lib/v2/index.cjs.js
`VueCompositionAPI.default` contains the object with the `install` function.
=> fix: cjs plugin install

lib/v2/index.cjs.js, lib/v2/index.esm.js, lib/v3/index.cjs.js, lib/v3/index.esm.js
remove `const` keyword from preventing compatibility issues
=> fix(lib/v2): export es6 syntax free es modules

lib/v2/index.cjs.js, lib/v3/index.cjs.js
Hi, Antony.
Yesterday's fix in #16  missed modification of arrow function in .cjs format lib outputs.
In case for low browser version compatibility, we also need to remove the definition of arrow functions.
=> chore: Remove arrow function declaration

.github/test.js, README.md, lib/index.iife.js, lib/v2/index.cjs.js, lib/v2/index.d.ts, lib/v2/index.esm.js, lib/v3/index.cjs.js, lib/v3/index.d.ts, lib/v3/index.esm.js, package.json
=> feat!: add Vue2 export and deprecate Vue

lib/index.d.ts
Hey,
I'm getting `node_modules/villus/node_modules/vue-demi/lib/index.d.ts(7,17): error TS7010: 'del', which lacks return-type annotation, implicitly has an 'any' return type.` error when I run `tsc`. I have a `vue 3` project which uses `@vueuse/core`.
Besides, `lib/v3/index.d.ts` already specifies `: void` as return type.
This change should fix `tsc` error.
=> fix: missing return type for del

lib/v2/index.cjs.js
Support edge case for VueDemi + Vue2 + CJS where `vue` has a default export which should be used to access `vue.use`
Closes: https://github.com/vueuse/vue-demi/issues/62
=> fix(lib/v2): edge case for vue-demi, vue2 and cjs

package.json
Fixes #66.
Node.js sees `.js` files as CJS modules if there's no `type: "module"` in `package.json`. So `index.esm.js` can't be imported from ES modules.
However, CJS modules can be imported from ES modules, named exports are also supported if it is statically analyzable.
So simply removing the `import` field should be just fine.
The `module` field is only used by bundlers, so keeping `.js` extension is harmless.
---
A better fix would be using a proper `.mjs` extension for the ESM build. But I haven't investigated #63, so I chose the safer approach.
=> fix: don't expose incorrect ESM entry in `exports`

README.md
Thanks for the very useful library.
I've created a package that uses this library and added it to "who are using this".
=> docs: add vue-word-highlighter to "who are using this"

package.json
This should allow using the beta versions of Vue without issuing a warning. Note I haven't been able to test it locally but in terms of semver it should work
=> chore: add unstable vue version to peer deps

package.json
This line was originally added by https://github.com/vueuse/vue-demi/pull/70 (at which point there were no `mjs`/`cjs` files).
Now that there are, this line is now preventing importing the `.mjs` file from within a module context in node.
The error generated is:
```
import { isRef, ref, watchEffect, computed, customRef, unref, inject, watch, getCurrentInstance, onMounted, onUpdated, shallowRef, getCurrentScope, reactive, markRaw, readonly, onBeforeUpdate, isVue2 } from 'vue-demi';
^^^
SyntaxError: Named export 'ref' not found. The requested module 'vue-demi' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'vue-demi';
const { isRef, ref, watchEffect, computed, …
```
=> chore: enable importing module in node

lib/v2/index.d.ts
I think It would make sense to expose `DebuggerEvent`, `VNode`, and `Plugin` types to make them compatible with Vue 3. I'm not sure if types should be exposed individually or if there should be an `export *`.
Other types that I think should be added:
- ComponentCustomProps
- AllowedComponentProps
- VNodeProps
There are useful for solar:
```ts
// example from vue-router-next (which doesn't require this as it is Vue 3 only)
export const RouterView = RouterViewImpl as unknown as {
new (): {
$props: AllowedComponentProps &
ComponentCustomProps &
VNodeProps &
RouterViewProps
$slots: {
default: (arg: {
Component: VNode
route: RouteLocationNormalizedLoaded
}) => VNode[]
}
}
}
```
=> feat(types): better compatibility

README.md
vue3-sketch-ruler plugin demo makes up for the fact that the previous demo was written with render function, and I directly used template to write and package
=> docs: add vue3-sketch-ruler to "Who are using this"

lib/index.iife.js
Add support for environments without a `window` in the iife version, which is supported by Vue itself.
=> fix(iife): support no-window environments

lib/index.iife.js
Sorry for the last problematic pr, but I still find myself needing to read the global-declared `Vue`, since no-window means no `this.Vue` so `vue-demi` is still in trouble trying to find a `Vue` instance.
For how I ran into this, the answer is UserScript `@require` tag, which doesn't have window access until the actual script is being executed.
=> fix(iife): try reading global declaration

lib/v2.7/index.d.ts
We need this fix so our Typescript projects that use this package can build properly.
There are duplicate Vue imports in this file.
=> fix(2.7): ts compilation error

package.json
When using "moduleResolution": "node16" in tsconfig, the pinia doesn't get type definition.
I add the types field in exports with package.json. It works well.
=> chore: types when esm exports

lib/index.iife.js
It would be useful to have `createApp` polyfill in vue-demi iife. For my use case, it’s useful in [testing for the Composition API using iife](https://github.com/intlify/vue-i18n-next/pull/1062/files#diff-83e7a30c07ab923ae44e2b18b9435c440d92da4f04183ee3bc1a7aa703a0a2cd).
=> fix(iife): createApp polyfill

lib/v2/index.mjs
When calling `install(VueInstance)` in versions < 2.7 the composition API was always being installed in the same Vue instance.
Now it add the compositionAPI on the Vue instance provided by parameter to the install function.
fix https://github.com/vueuse/vue-demi/issues/184
=> fix(<2.7): Install composition API on provided vue instance

lib/index.iife.js
=> fix(iife): add hasInjectionContext

lib/v2.7/index.cjs, lib/v2.7/index.mjs
=> fix(2.7): correct source for hasInjectionContext

lib/v2/index.mjs
VueCompositionAPI.getcurrentInstance is not a function
=> fix(<2.7): hasInjectionContext error

package.json
Insufficient installation directory permissions can cause script execution to fail
在某些环境中，postinstall文件可能执行权限不足，而postinstall命令无容错处理可能会导致安装环节报错，影响整体流程。
=> fix(scripts): fix error in install

lib/index.iife.js
I want to use vue-demi through `<script type="module" src"..."></script>`
=> feat: support `<script type="module" src"...">`
